### ISSUE TITLE
Nekosama extension error

### ISSUE THREAD

**Issue by mobby45** [almightyhak/aniyomi-anime-repo#1]
The french extension named nekosama gives out an error about the host name : nekosama.frhttps or I think it should be https://nekosama.fr even changing domain name don't change anything

**Comment by mobby45** [comment]
it does the same with animecat domain

**Comment by almightyhak** [comment]
I'm sorry but i can't reproduce the problem are you sure you're using my repo?

**Comment by mobby45** [comment]
Yeah, now i got the error Java.NullPointerException

**Comment by mobby45** [comment]
or i get Unable to resolve host "animecat.nethttps" : No address associated with hostname for example, i search toaru no kagaku no railgun and i got no episodes or even cover picture, (there's also another extension named anime sama again french, who cause problem but it's just cover problem, there's not)

**Comment by almightyhak** [comment]
ah i see it now, it's gonna take a bit to fix cus i have exams right now and i'm still new to coding

**Comment by mobby45** [comment]
no worry men, take ur time, just to know what are ur nationality ? and there's also error with AniSama and AnimeSama too which i find it bad 👎

**Comment by almightyhak** [comment]
I think the culprit is the websites updating/changing intentionally to break the extensions and I prefer not to say where i'm from but I will say that I'm asian

**Comment by mobby45** [comment]
okay and do u think u could update the extensions ?

**Comment by almightyhak** [comment]
I'll try but no guarantees tho since this is actually my first coding project that I've uploaded to the internet

**Comment by mobby45** [comment]
https://neko-sama.fr or https://animecat.net for NekoSama Extension
for anime sama extension : https://anime-sama.fr ps: it's just certain cover
Anisama extension : https://animesz.xyz it changes to that

**Comment by almightyhak** [comment]
I'll see what I can do

**Comment by mobby45** [comment]
ok thanks men/women :D

**Comment by almightyhak** [comment]
Fyi I'm a dude

**Comment by mobby45** [comment]
okay me too then have good luck for ur exams :)

**Comment by almightyhak** [comment]
Thanks :)

**Comment by mobby45** [comment]
Also for AniSama, there's a bug where we can't search is shows always the same anime

**Comment by almightyhak** [comment]
I'll try to find the original source code so that everyone can help

**Comment by mobby45** [comment]
yeah could be good :)

**Comment by mobby45** [comment]
uh no ? it's aniyomi extensions ? https://github.com/aniyomiorg/aniyomi-extensions no ?

**Comment by almightyhak** [comment]
It technically is but 99% of the extensions has been taken down by sony

**Comment by mobby45** [comment]
oh ok, SOny those who made the Playstation??

**Comment by mobby45** [comment]
it's shit to do that, aniyomi isn't the creator of those

**Comment by Lolen10** [comment]
> oh ok, SOny those who made the Playstation??

Sony actually own Crunchyroll. So they have an interest in the extensions not to be existing.

**Comment by mobby45** [comment]
Seems logic

**Comment by mobby45** [comment]
else if u want and u have a tutorial to fix the extensions issue, i can help my friend :)

**Comment by mobby45** [comment]
The extension named AnimeVostFr also have errors unexpected Jason error
